# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        path: branch

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Clone output branch
      uses: actions/checkout@v3
      with:
        ref: site
        path: output
        token: ${{ secrets.PUSH_TOKEN }}

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Gradle Build and Run
      working-directory: ./branch
      run: |
        ./gradlew run --args="--output ../output/docs"

    - name: Commit and Push changes
      uses: EndBug/add-and-commit@v9
      with:
        cwd: ./output
        default_author: github_actions
        message: 'Automated Build'
